### ISSUE TITLE
load weights from pre-trained model

### ISSUE THREAD

**Issue by JanaGeyer** [calico/basenji#102]
Hi, thanks for creating this very useful tool.

I would like to load the pre-trained weights from this model https://storage.googleapis.com/basenji_barnyard/model_human.h5 and use them to continue training a model based on my ATAC-seq data for a certain human blood type. Since I do not have an extremely large Dataset, I am hoping that not having to start the training from scratch could improve my predictions and speed up the training.

I noticed that basenji_train.py has the options --restore and --trunk. Therefore, I used the params_human.json (basenji/manuscripts/cross2020/params_human.json), changed the number of tasks in the head in order to fit to my data and then started running basenji_train.py script with the options --restore model_human.h5 -- trunk
Doing that, I received the following error:
_ValueError: You are trying to load a weight file containing 61 layers into a model with 60 layers._

Is this the correct way to make use of weights from a pre-trained model? If yes what am I doing wrong here?

Thank you very much for your help!

**Comment by davek44** [comment]
Hi, sorry this is poorly documented. I haven't figured out how to make tf.keras do the right thing here. My approach is to resave only the trunk of the model using the following command,

`$BASENJIDIR/bin/save_model.py -t params_human.json model_human.h5 model_human_trunk.h5`

Then provide model_human_trunk.h5 in your basenji_train.py command, with the modified params file.

**Comment by JanaGeyer** [comment]
Thank you very much! That worked.
