### ISSUE TITLE
Target Description

### ISSUE THREAD

**Issue by khoapip** [calico/basenji#104]
Hi! Thank you for the awesome work. I am trying to apply your preprocessed data to solve another problem.

After I tried converting the tfrecord files of human data to numpy array using your code, each sample in the target has a dimension of (896, 5313).  Is the order of those 5313 features consistent to the order of the identifiers listed in https://github.com/calico/basenji/blob/master/manuscripts/cross2020/targets_human.txt  ?

Thank you so much.

**Comment by davek44** [comment]
Yes, the order should be consistent.

**Comment by khoapip** [comment]
That's great! Thank you again for the great project.
