### ISSUE TITLE
Reproducing Saluki

### ISSUE THREAD

**Issue by cwadaniels7** [calico/basenji#112]
Hi, 

I am working on training the Saluki model using the same data as used in the Saluki paper. I've been able to start the model by doing the following

` ! saluki_train.py -o ~/single_output ~/deeplearning/train_gru/params.json ~/deeplearning/train_gru/f1_c0/data0`

However, my hunch is that this would train the model only on a subset of subset of the data (does f = fold and c = cross validation?). 

Presumably if I want to train saluki on the entire dataset

`! saluki_train_folds.py -o ~param_file_path.json ~data_path`

What would be the relative paths for the parameters and data?

Or if I've missed something explaining the file structures please let me know. I'm just looking to recapitulate your results before running the model on my own data.

**Comment by vagarwal87** [comment]
Hi Carter, I'm happy to help you if I understand your final goals a bit better.

Is your goal to use the final model to generate predictions? If so, we have found that ensembling the predictions from our pre-trained models works well. Why not skip training altogether? All pre-trained models are provided with source code on how to use them.

Or is your goal to reproduce the model training for its own sake? If so, why not just using the train/validation/test partition from one of the  folds we provide? You're right that f=folds (0-9) and c = trial (0-4). The params.json file is provided in each fold/trial combo and is the same.

**Comment by cwadaniels7** [comment]
At this time, my goal currently is to reproduce the model training for its own sake. Thank you for clarifying the setup of the data structures. I should be able to proceed. 

Your other answer is also helpful as I will be working my way up to making some predictions. 

I always like to make sure I understand how a model was/is trained before I start trying to make predictions from any previously trained models. 

Thanks!

**Comment by vagarwal87** [comment]
Great, hope it goes smoothly & let us know if you bump into any more difficulties!

**Comment by cwadaniels7** [comment]
Hi I've managed to generate predictions for my data but want to confirm the approach I took is correct:

1.  A TFR was generated in which for each gene of interest the following was record into a dictionary: sequence length, one-hot encoded sequence , one-hot encoding of where codons started in the ORF, one-hot encoding of splice sites, and then targets 
2. The TFR was then fed to saluki_test.py along with the params.json and model0_best.h5 of each fold/trial combination (i.e., for each trial within each fold a prediction was generated for each gene of interest)
3. I then imported the data back into my coding environment to generate graphs and do further analyses on the predictions. 

A few questions:

1. I one-hot encoded the mRNA (ACGU)  but noticed that much of the dna io in basenji is working with the DNA; can you confirm it is the mRNA that should be one-hot encoded?
2. it was unclear to me what served as the targets in the dictionary that goes into the TFR; in my case I set targets equal to the obtained half-life for the gene of interest; can you clarify what the "target" is?
3. should the N padding be included in my one-hot encoding or does Saluki handle that? If I need to handle the N padding what should Ns be encoded as (I believe in the basenji data I saw 0.25)?

I realize some of these questions may be basic, but just want to get clarity on these steps before accepting the predictions. Thank you for your time and if you have any other advice for generating predictions I greatly appreciate it.

**Comment by vagarwal87** [comment]
That sounds correct overall. Only modification I would make is that you should average the predictions from all models/folds afterwards to simplify the prediction. 

1) yes, the mRNA should be one-hot encoded in the same way as DNA (U=T from code's perspective) -- only difference is that the input matrix is supplemented with info about 1st codon positions and 5' splice site positions. 
2) target is simply the label. if you're just interested in generating predictions, it doesn't matter. if there are labels, however, it can tell you statistics on r^2, correlation, etc between predictions and labels. for our experiments using cross-validation, we had the label to evaluate against. If you have no label, you can just do a forward pass through the pre-trained network to acquire the prediction.
3) N padding is basically just 0's throughout after the 3'-most nucleotide of the mRNA. By default when you initialize a numpy array in the correct shape, it can have all zeros, and then you can populate the 5' end of the matrix with the sequence, codon, and splicing info.

if you are concerned about how to generate the predictions, we have many examples in my saluki_paper Github (for example Fig6 folder) as well which show the averaging process and code to generate predictions.
