### ISSUE TITLE
ValueError in restoring model for akita 

### ISSUE THREAD

**Issue by j3gu** [calico/basenji#115]
Hello, 
I am following the tutorial to load model and make predictions. However, I am running into the following error.
"ValueError: You are trying to load a weight file containing 83 layers into a model with 42 layers."
I am wondering if the parameter file matches with the trained model downloaded from get_model.sh.

**Comment by davek44** [comment]
Hi, I'm guessing that you're referring to this notebook: https://github.com/calico/basenji/blob/master/manuscripts/akita/explore_model.ipynb. If not, please clarify. I'm not able to replicate the error, so try pulling the latest code from master and re-downloading the model. If you're still getting an error, send more details.

**Comment by j3gu** [comment]
Hi David,
Yes, that is the notebook I am referring to. I did what you suggested and now I can get it running. Somehow the previous code loaded "model_5" instead of "model_3", even though the same model and params.json file were used. I am curious what makes the difference. The lines of codes seem to be the same between the two versions.

Thanks.
Best,
Jing
