### ISSUE TITLE
Hard coded conda prefix

### ISSUE THREAD

**Issue by SuhasSrinivasan** [calico/basenji#126]
Thank you for making this available.

Just wanted to note the prefix included from the developer machine.

https://github.com/calico/basenji/blob/8f86a2df0c314e6e7cb7ce12ccf8399f4f93b71c/prespecified.yml#L438

**Comment by davek44** [comment]
Does this create an error for you? My understanding from this thread was that it didn't https://stackoverflow.com/questions/41274007/anaconda-export-environment-file

**Comment by SuhasSrinivasan** [comment]
Thank you!
