### ISSUE TITLE
Cannot Download from Basenji Google Cloud

### ISSUE THREAD

**Issue by yhzq** [calico/basenji#131]
Hi authors, 

Thank you for your impressive and groundbreaking work in gene expression prediction. Recently, when I tried to download data from your google cloud repository (https://console.cloud.google.com/storage/browser/basenji_barnyard), it shows:

> Bucket is a requester pays bucket but no user project provided.

Could you remove the "requester pay" restriction in the bucket? Thank you!

**Comment by davek44** [comment]
Hi Eric, the cost to my organization of paying for user downloads of the training data became too large. You’ll have to make a Google cloud account attached to a payment method to download it now. My understanding is that this will be a small cost to you.

**Comment by yhzq** [comment]
Thank you for the quick response. It's quite understandable.
