### ISSUE TITLE
Test gene expression predictions link is broken 

### ISSUE THREAD

**Issue by obada-alzoubi** [calico/basenji#135]
Hi there, 
The link for [Test gene expression predictions.](https://github.com/calico/basenji/blob/master/tutorials/genes.ipynb)] is broken. There is one version of the gene tutorial in the archive, but not sure if there is a reason for that. 
Thank you so much!

**Comment by davek44** [comment]
Yes, that code is deprecated. We're currently overhauling this, but it isn't finished yet. I removed the link from the README
