### ISSUE TITLE
tutorial broke

### ISSUE THREAD

**Issue by mepster** [calico/basenji#141]
The following line in the [preprocessing tutorial](https://github.com/calico/basenji/blob/master/tutorials/preprocess.ipynb)

! basenji_data.py -d .1 -g data/unmap_macro.bed -l 131072 --local -o data/heart_l131k -p 8 -t .1 -v .1 -w 128 data/hg19.ml.fa data/heart_wigs.txt

is broken. I believe because a recent [checkin of basenji_data.py](https://github.com/calico/basenji/commit/54e9dba6448a2d54544ad5d16c6c73149d33381f) changed the name of the sample_pct option from -d to -s 

Thanks for making basenji available!

**Comment by davek44** [comment]
I pushed a fix. Thanks!
