### ISSUE TITLE
akita_data_read.py % string make target to zero

### ISSUE THREAD

**Issue by r1cheu** [calico/basenji#145]
```
  File "akita_data_read.py", line 158, in main
    print("WARNING: %s >50% bins filtered, check:  %s. " % (genome_hic_file, mseq_str))
ValueError: unsupported format character 'b' (0x62) at index 17
```
hi, the code above will cause a ValueError, due to the `except ValueError:` below, will make the target to 0.

**Comment by davek44** [comment]
I'm not sure that I understand. In your use case, does 'genome_hic_file' not contain a normal filename string?

**Comment by r1cheu** [comment]
just python recognize the % sign in the `>50% bin` as `%b` and casue valueerror.

**Comment by davek44** [comment]
Ah, got it. I pushed a fix. Thanks!
