### ISSUE TITLE
Can I apply Basenji's series of functions to the Enformer model?

### ISSUE THREAD

**Issue by zhanxiangzong** [calico/basenji#149]
Thank you for providing a series of excellent models.
In the past, we conducted a series of research using your developed Basenji model, which had a complete and user-friendly set of functions for preprocessing, training, testing, and predicting mutation effects. However, it seems that your newly developed Enformer model does not have these functions. 
Can I apply the series of functions from Basenji to Enformer? If yes, how should the params.json file be written?

**Comment by davek44** [comment]
HI, we don't have an exact replica of Enformer using this codebase, but you should be able to create one. If you start with Basenji2 params, and replace the dilated convolution tower with a transformer tower (https://github.com/calico/basenji/blob/master/basenji/blocks.py#L1262), you're most of the way there.

**Comment by zhanxiangzong** [comment]
Thank you very much for your helpful suggestion! I will try to follow your instructions and modify the params.json file accordingly. I appreciate your assistance in creating an Enformer model using your codebase.
