### ISSUE TITLE
pygene installation

### ISSUE THREAD

**Issue by hamanakakohei** [calico/basenji#162]
Hi,

Thank you for developing such a great tool!
"pygene" is imported in "saluki_ssd.py".
I would like to use this, but where can I install this?
I could not find it on the internet.
I am looking forward to hearing from you.

**Comment by davek44** [comment]
Oops, that's a personal package that you can find here: https://github.com/davek44/utility/blob/master/pygene.py

We're refactoring the code now, and will take this into account. Thanks

**Comment by hamanakakohei** [comment]
Thanks a lot!!
