### ISSUE TITLE
How to set different GPU No. ?

### ISSUE THREAD

**Issue by houruiyan** [calico/basenji#178]
Hi Author, 

I want to run your demo code. My server have four GPU, however other colleagues also are running their own software in GPU 0. Then how can I set the number which I want to run basenji ? 
Hope to get your reply. Thank you!

Best regards,
Ruiyan

**Comment by davek44** [comment]
Hi Ruiyan, that’s more of a TensorFlow question than a Basenji question. Unfortunately, I don’t know how to do it.

**Comment by houruiyan** [comment]
ok , thank you.  
`export CUDA_VISIBLE_DEVICES=1
`
This code can be used to set as an indirect method if anyone has the same problem as me.
