### ISSUE TITLE
Pre-process tutorial file not working

### ISSUE THREAD

**Issue by riapai** [calico/basenji#181]
The issue is occurring in /basenji/tutorials/preprocess.ipynb. 
In line 4:` ! basenji_data.py -s .1 -g data/unmap_macro.bed -l 131072 --local -o data/heart_l131k -p 8 -t .1 -v .1 -w 128 data/hg19.ml.fa data/heart_wigs.txt` There is no data/file generated in **data/heart_l131k**. Because of this the rest of the tutorial cannot be completed.

**Comment by rubensolozabal** [comment]
Hi, it works to me, you just need to change the paths, e.g. basenji_data.py - > bin/basenji_data.py

**Comment by davek44** [comment]
Yes, you have to specify the path or add the bin/ directory to your $PATH variable, which I recommend in the README.
