### ISSUE TITLE
tutorial training with --sample 0.05

### ISSUE THREAD

**Issue by zyj1729** [calico/basenji#182]
I followed the tutorial.ipynb and use --sample 0.05 to train a test model, the training stops in 38 epochs. The results seem far off. Is it because I only used 5% training data? 
![Screenshot 2023-10-23 at 10 58 12 PM](https://github.com/calico/basenji/assets/36032734/0325d6cc-9a3d-42d3-a077-1853d43b59e8)
![Screenshot 2023-10-23 at 11 00 03 PM](https://github.com/calico/basenji/assets/36032734/f6e8a9f5-e5dc-4d4e-bafa-887d9b817a87)

**Comment by zyj1729** [comment]
I realize this is the sample size thing. Once I remove --sample 0.05, the results make sense now. I would still suggest to maybe explicitly mention at the end of tutorial.ipynb that we shouldn't expect meaningful results using --sample 0.05. Because I thought the model loaded to explore_model.ipynb was the one trained from tutorial.ipynb.

**Comment by zyj1729** [comment]
close this

**Comment by amingc3** [comment]
Hello, I've also encountered this issue. I would like to ask, after you removed '--sample 0.05', how many training iterations did you perform on the author-provided data to achieve a Pearson correlation coefficient of 0.6?

**Comment by mchoccie** [comment]
Hey did you manage to run this at all. I have sample 0.75, but looking at the live training results it doesn't seem like the model is ever going to achieve a pearson correlation coefficient of 0.6

> Hello, I've also encountered this issue. I would like to ask, after you removed '--sample 0.05', how many training iterations did you perform on the author-provided data to achieve a Pearson correlation coefficient of 0.6?
