### ISSUE TITLE
Making Akita predictions for different bin size

### ISSUE THREAD

**Issue by shu-z** [calico/basenji#183]
Hi, I'm interested in making Akita predictions for contact maps with exactly 5000bp length bins (instead of 2048bp). How do you suggest going about this? Thank you!

**Comment by gfudenberg** [comment]
Hi Shu, 
I think you'd need try to re-specify a model architecture that pools to the desired bin size, then re-do data preprocessing and model training in that setting.
Hope that helps!

**Comment by shu-z** [comment]
Sounds good. Thank you!
