### ISSUE TITLE
Seeking Guidance on bam_cov.py Parameters

### ISSUE THREAD

**Issue by zhanxiangzong** [calico/basenji#185]
Hello, I want to express my sincere gratitude for providing this software. Currently, I'm facing an issue while using bam_cov.py to convert BAM files to BigWig. It seems that using only the default parameters doesn't achieve all the preprocessing steps outlined in your paper (for instance, the -g default in bam_cov.py is set to False).
I would greatly appreciate guidance on how to adjust the parameters in bam_cov.py to ensure that the data preprocessing aligns with the standard procedures outlined in your paper. Specifically for CAGE, DNase-seq, ATAC-seq, and ChIP-seq, are there specific parameter settings? Also, are there any parameters that should be modified based on different species? 
Thank you very much for your time and support.

**Comment by davek44** [comment]
Here are some rough recommendations, but note that most of these are chosen somewhat subjectively. I can't think of a reason to modify them across different species.

CAGE: bam_cov.py --clip_multi 12 -m 3 -s 4 --smooth_out 2 --strand 
DNase/ATAC/ChIP: bam_cov.py --clip_multi 12 -g -m 3 -s 16 --smooth_out 8
For ATAC, add -v 4 -w 5
For ChIP, add -c

**Comment by zhanxiangzong** [comment]
Thank you very much for your help.
