### ISSUE TITLE
Prepare data 

### ISSUE THREAD

**Issue by amingc3** [calico/basenji#191]
How is the hg38_gaps_binsize2048_numconseq10.bed file generated? Is it possible to generate a bed file with a binsize of 5kb?

**Comment by gfudenberg** [comment]
Hi @amingc3 we used the following approach: https://gist.github.com/gfudenberg/6c3219065217d2251a9c5ce31e8596ce. If you processed all data into coolers with 5kb bins, then this could create a bed file with 5kb bins.
