### ISSUE TITLE
Basenji installation issues

### ISSUE THREAD

**Issue by seraphimangel77** [calico/basenji#194]
I followed the commands: conda env create -f prespecified.yml
conda install tensorflow (or tensorflow-gpu)
python setup.py develop --no-deps

to install Basenji, and I installed all the required packages. However, when I try to import basenji, I always get the error: ModuleNotFoundError: No module named 'basenji'. What could be the problem? Could you advise on how to resolve this issue?"

Thank you so much! Look forward your response! Thanks!

**Comment by seraphimangel77** [comment]
If possible, could you do me a huge favor that you provide a Docker image? Thank you so much!

**Comment by seraphimangel77** [comment]
I also tried the other two installation methods you provided, which both showed successful installations, but I still can't import.
<img width="552" alt="Weixin Image_20240515023450" src="https://github.com/calico/basenji/assets/109591842/138e6642-06e0-4cdb-b8e0-20133202e7dc">
<img width="490" alt="Weixin Image_20240515023532" src="https://github.com/calico/basenji/assets/109591842/e01e3c61-1538-462b-a0c6-f74c362c7e53">

**Comment by davek44** [comment]
Hi, please move to our new codebase here: https://github.com/calico/baskerville

**Comment by seraphimangel77** [comment]
Hi, Is this where Basenji is installed? It seems I can't find Basenji in here?

Thank you
