### ISSUE TITLE
Error from basenji import genome

### ISSUE THREAD

**Issue by seraphimangel77** [calico/basenji#197]
Hi,

Thank you for so excellent work.

When I run the manuscripts/akita/tutorial.ipynb

I encount an error

<img width="617" alt="3" src="https://github.com/calico/basenji/assets/109591842/5759deae-633b-425a-a05c-00e78a33482a">

The code I use is 

! /project/pathology/Mani_lab/s231294/Data/Akita/akita_data.py --sample 0.05 -g /project/pathology/Mani_lab/s231294/Data/Akita/data/hg38_gaps_binsize2048_numconseq10.bed -l 1048576 --crop 65536 --local -o /project/pathology/Mani_lab/s231294/Data/Akita/data/1m --as_obsexp -p 8 -t .1 -v .1 -w 2048 --snap 2048 --stride_train 262144 --stride_test 32768 /project/pathology/Mani_lab/s231294/Data/Akita/data/hg38.ml.fa /project/pathology/Mani_lab/s231294/Data/Akita/data/microc_cools.txt

I install the basenji with https://github.com/calico/basenji/tree/master

Can you do me a huge favor that how to resolve this matter?

What's wrong with my basenji?

Thank you so much for the time and help

Best,
Cecelia

**Comment by davek44** [comment]
Hi, it doesn't appear that the package is importable through your python. Make sure you perform these steps:

 export BASENJIDIR=~/code/Basenji
 export PATH=$BASENJIDIR/bin:$PATH
 export PYTHONPATH=$BASENJIDIR/bin:$PYTHONPATH
 
 We have made installation work much better in our new repository where we do active development: https://github.com/calico/baskerville
