### ISSUE TITLE
Fail to intall basenji

### ISSUE THREAD

**Issue by MQMQ2018** [calico/basenji#20]
Dear Authors: 
I tried to install basenji as instruction from README.md, 
And I input command as below:
python setup.py develop --install-dir=/software/python3lib
And the Error messenger is showed as below:
#======#
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c: In function ‘__pyx_f_4h5py_4defs_H5Sget_regular_hyperslab’:
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c:31571:15: warning: implicit declaration of function ‘H5Sget_regular_hyperslab’ [-Wimplicit-function-declaration]
   __pyx_t_1 = H5Sget_regular_hyperslab(__pyx_v_spaceid, __pyx_v_start, __pyx_v_stride, __pyx_v_count, __pyx_v_block); if (unlikely(PyErr_Occur
               ^
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c: In function ‘__Pyx_modinit_function_export_code’:
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c:40634:67: error: ‘__pyx_f_4h5py_4defs_H5Pset_virtual_view’ undeclared (first use in this function)
   if (__Pyx_ExportFunction("H5Pset_virtual_view", (void (*)(void))__pyx_f_4h5py_4defs_H5Pset_virtual_view, "herr_t (hid_t, H5D_vds_view_t)") <
                                                                   ^
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c:40634:67: note: each undeclared identifier is reported only once for each function it appears in
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c:40635:67: error: ‘__pyx_f_4h5py_4defs_H5Pget_virtual_view’ undeclared (first use in this function)
   if (__Pyx_ExportFunction("H5Pget_virtual_view", (void (*)(void))__pyx_f_4h5py_4defs_H5Pget_virtual_view, "herr_t (hid_t, H5D_vds_view_t *)")
                                                                   ^
In file included from /opt/apps/tools/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /opt/apps/tools/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/easy_install-567tun7k/h5py-2.8.0/h5py/api_compat.h:26,
                 from /tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c:611:
/tmp/easy_install-567tun7k/h5py-2.8.0/h5py/defs.c: At top level:
/opt/apps/tools/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
error: Setup script exited with error: command 'gcc' failed with exit status 1
#==========#

Could you help to give me some tips how to figure it out? Thank you so much. 

BEst,
Qi

**Comment by davek44** [comment]
Hi Qi, the install seems to be choking on the installs for h5py and/or tensorflow. I would try installing those packages manually.

**Comment by MQMQ2018** [comment]
Dear David
Thank you so much, David. Your suggestion really works!
I have also responded at Github. Thank you so much again.
Best,
