### ISSUE TITLE
how to use the RNA_TPM.bed.gz expression train a Basenji model

### ISSUE THREAD

**Issue by yunaibiao** [calico/basenji#202]
Hello, dear author. I’d like to use the RNA_TPM.bed.gz expression file along with ATAC and other data to train a Basenji model. Is that possible? If so, how should I go about it to perform in silico saturation mutagenesis analysis on variant sites?

**Comment by davek44** [comment]
Hi, I'm not familiar with that data format, but we have new work modeling RNA-seq that you can read about here: https://www.biorxiv.org/content/10.1101/2023.08.30.555582v1
