### ISSUE TITLE
Where can I find the "data/heart_l131k.bed" in Preprocess new datasets for training part in Turorial? Thank you so much.

### ISSUE THREAD

**Issue by MQMQ2018** [calico/basenji#22]
Dear David, 

Could you guide me where can I find the "data/heart_l131k.bed" in Preprocess new datasets for training part in Turorial? Thank you so much.

**Comment by davek44** [comment]
That specifies the name of an output file. It won't exist until you run the program.

**Comment by MQMQ2018** [comment]
Thank you, David. You are so helpful.
Best,
Qi
