### ISSUE TITLE
Barcoded Bam Files as inputs to bam_Cov.py

### ISSUE THREAD

**Issue by jgockley62** [calico/basenji#26]
Hi,

I had an issue of inputing barcoded bam files to the bam_Cov.py script where the bigWig files were essentially empty except for a header. I've tracked the issue at least part of the way down to being an issue of tags. For example, line 1205: _if (not align.has_tag('NH') or align.get_tag('NH')==1) and not align.has_tag('XA'):_ 

If I understand correctly this is essentially asking if the read is uniquely aligned, but my BAM file doesn't have NH or XA tags. I can use AS (Alignement score of primary) == XS (Alignment score to suboptimal alignement) to determine if a read is essentially uniquely mapping. But I was wondering if you could point out other points in the script I should be worried about or if you had an alternative strategy besides re-alignment to deal with this issue.

Thanks!

**Comment by davek44** [comment]
Sorry, that script is a little over-optimized for my setup. Right now, I'm using the BWA aligner, which writes all of the multi-mappers into one BAM entry. With Bowtie2, I had a separate script to add the NH tag. Tophat uses the NH tag, and I developed a bunch of methods to make use of it. I can pass that script along if you want to use Bowtie2. But BWA is probably the easiest way to proceed.

**Comment by jgockley62** [comment]
Sounds great. Are you using a specific set of bwa flags that produce similar results to Bowtie2's --very-sensitive mode specified in the pre-processing tutorial (preprocess.ipynb), just running under default parameters, or using a another set of flags?

**Comment by davek44** [comment]
I don't have a perfect feel for the BWA parameters yet, but I've been increasing -c to 1000 and giving -h 2,1000 to try to get more action from multi-mappers. I'd be happy to hear your experience if you learn anything there.

**Comment by davek44** [comment]
Scratch that. I misunderstood the "-h" option. I'm using "-h 16" now.
