### ISSUE TITLE
Tutorial sad.ipynb not working

### ISSUE THREAD

**Issue by yudongqiu** [calico/basenji#28]
Hi Basenji Developers, thanks a lot for the great project. I ran into a list of issues trying to reproduce the `sad.ipynb` tutorial.

I was able to download the additional files in the first three blocks in the notebook. Then errors occur in the block when executing this command:
```
basenji_sad.py -f data/hg19.ml.fa -g data/human.hg19.genome -l 131072 -o output/rfx6_sad --rc -t data/heart_wigs_index.txt models/params_small.txt models/heart/model_best.tf data/rs339331.vcf
```
I was able to solve the first three errors but not the fourth. Any help is greatly appreciated.

1. the `zarr` package is required but not listed in the `setup.py`. I installed it by `pip install zarr`.

2. `HG19` environmental variable is required even if `-f data/hg19.ml.fa` if specified. I solved it by setting an empty string like `export HG19=''`

3. Error occurs when the script loaded the index file as dataFrame, i.e. `df = pd.dataFrame("data/heart_wigs_index.txt")` and tried to access the `df.identifier` and `df.description`. I think this is because `data/heart_wigs_index.txt` created in the tutorial does not have a first row of column names. I manually added `identifier` for the 2nd and `description` for the 4th column based on my guess.

4. Error when building a TF tensor, says the dimension is wrong:
```
>>> ~/codes/basenji/bin/basenji_sad.py -f data/hg19.ml.fa -g data/human.hg19.genome -o output/rfx6_sad --rc -t data/test_index.txt models/params_small.txt models/heart/model_best.tf data/rs339331.vcf
{'batch_size': 4, 'batch_buffer': 4096, 'link': 'softplus', 'loss': 'poisson', 'optimizer': 'adam', 'adam_beta1': 0.97, 'adam_beta2': 0.98, 'learning_rate': 0.002, 'num_targets': 3, 'target_pool': 128, 'cnn_dropout': 0.1, 'cnn_filter_sizes': [20, 7, 7, 7, 3, 3, 3, 3, 3, 3, 3, 1], 'cnn_filters': [128, 128, 192, 256, 256, 32, 32, 32, 32, 32, 32, 384], 'cnn_pool': [2, 4, 4, 4, 1, 0, 0, 0, 0, 0, 0, 0], 'cnn_dilation': [1, 1, 1, 1, 1, 2, 4, 8, 16, 32, 64, 1], 'cnn_dense': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]}
Targets pooled by 128 to length 8
Traceback (most recent call last):
  File "/home/qyd/codes/basenji/bin/basenji_sad.py", line 474, in <module>
    main()
  File "/home/qyd/codes/basenji/bin/basenji_sad.py", line 162, in main
    embed_penultimate=options.penultimate, target_subset=target_subset)
  File "/home/qyd/codes/basenji/basenji/seqnn.py", line 51, in build_feed
    target_subset=target_subset)
  File "/home/qyd/codes/basenji/basenji/seqnn.py", line 75, in build_from_data_ops
    save_reprs=True)
  File "/home/qyd/codes/basenji/basenji/seqnn.py", line 238, in build_predict
    seq_length - batch_buffer_pool, :]
  File "/home/qyd/codes/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 206, in __sub__
    return Dimension(self._value - other.value)
  File "/home/qyd/codes/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 42, in __init__
    raise ValueError("Dimension %d must be >= 0" % self._value)
ValueError: Dimension -24 must be >= 0
```
I found that the dimension `seq_length - batch_buffer_pool` is `-24` because `seq_length` is 8 and `batch_buffer_pool` is 32.

Hopefully the above information make sense, and the tutorials can be updated to work again. Thanks!

**Comment by davek44** [comment]
Hi, I just pushed updated tutorials. Try again and let me know if it works now for you

**Comment by yudongqiu** [comment]
@davek44 Thanks a lot for the fix! I just tested that the tutorial is working now!
