### ISSUE TITLE
Can't import util and slurm in basenji_data.py

### ISSUE THREAD

**Issue by ChendiWang** [calico/basenji#32]
Hi David,

Thank you so much for sharing the Basenji code. I was trying to run the preprocess.py from the tutorial, but I ran into the error that:

ModuleNotFoundError: No module named 'util'
ModuleNotFoundError: No module named 'slurm'

Do you know where I can find these two packages?

Thanks!

**Comment by ChendiWang** [comment]
I found them in your utility repo!

**Comment by davek44** [comment]
Thanks for identifying that. I moved util into the package, and caught the slurm exception. The slurm code is tailored specifically to our setup here.

**Comment by ChendiWang** [comment]
Thanks for updating that! I see, I only used local running so I didn't use the slurm exception.

**Comment by davek44** [comment]
Yup, that's the way to go. If you or anyone else who comes across this issue in the future would like to tailor the slurm code to their own cluster, I'd be happy to help with that.

**Comment by ChendiWang** [comment]
Thanks a lot Dave! I will come back for your help if I have problem using slurm in the future.

**Comment by Licko0909** [comment]
> I found them in your utility repo!

Hello, I have encountered the same problem, there is no util, how can I solve it, thank you very much!

ModuleNotFoundError: No module named 'util'

**Comment by davek44** [comment]
I've added that code to the repo here: https://github.com/calico/basenji/blob/master/basenji/util.py

Try pulling the latest and re-running. If it still doesn't work, let me know which script you're working with.

**Comment by Licko0909** [comment]
It can work! thank you! But I have other questions, I need to open a new question interface.
