### ISSUE TITLE
After running `perprocess.ipynb`, there is no "tfr file and h5 file" generated, only some empty err files. The program runs without error

### ISSUE THREAD

**Issue by Licko0909** [calico/basenji#33]
Hello!  

After running `perprocess.ipynb`, there is no "tfr file" generated, only some empty err files. The program runs without error, as shown below:

![image](https://user-images.githubusercontent.com/27897166/55523103-44d18b80-56ba-11e9-965c-cef7bbedb824.png)
![image](https://user-images.githubusercontent.com/27897166/55523208-a72a8c00-56ba-11e9-8b4b-bbfdd1245092.png)

![image](https://user-images.githubusercontent.com/27897166/55523149-764a5700-56ba-11e9-85b0-7e03070ad871.png)
![image](https://user-images.githubusercontent.com/27897166/55523154-79454780-56ba-11e9-9fc1-eeb766314788.png)

**Comment by Licko0909** [comment]
Thank you! After pondering for a while, I found a solution! The main reason is the lack of file permissions. I set `chmod 777 *` to all the files in the `basenji/basenji` and `basenji/bin` folders, and then run the code to get the tfr file and the h5 file. I don't know what caused it.
![image](https://user-images.githubusercontent.com/27897166/55525024-f922e000-56c1-11e9-9a3b-ef28785b580c.png)
![image](https://user-images.githubusercontent.com/27897166/55525034-04760b80-56c2-11e9-9ef5-22e58ec9db4f.png)
![image](https://user-images.githubusercontent.com/27897166/55525042-0f30a080-56c2-11e9-94c0-67f532e98997.png)

**Comment by FaizRizvi** [comment]
Hello Dr. Kelley,

Sorry to bother you. I am trying to process the data with the same way as you have shown here in the preprocess.ipynb. I have been able to produce *.h5 but I am unable to produce any *.tfr files as shown below:
<img width="1035" alt="Screen Shot 2019-08-05 at 12 01 20 PM" src="https://user-images.githubusercontent.com/47329147/62513178-0e7f5680-b7e9-11e9-9f4d-baa23d4ded2f.png">
<img width="1017" alt="Screen Shot 2019-08-05 at 12 02 19 PM" src="https://user-images.githubusercontent.com/47329147/62513183-10e1b080-b7e9-11e9-8585-f49e265bc0fd.png">

When I take a closer look at the 0.err in the seqs_cov/ folder I get the following error: 
<img width="1268" alt="Screen Shot 2019-08-06 at 1 18 44 AM" src="https://user-images.githubusercontent.com/47329147/62513216-340c6000-b7e9-11e9-8a99-acc475659ce8.png">

The test-0.err and the train-0.err files have the following error:
<img width="1269" alt="Screen Shot 2019-08-06 at 1 24 07 AM" src="https://user-images.githubusercontent.com/47329147/62513286-7fbf0980-b7e9-11e9-8a5f-6d58996162bc.png">

I would greatly appreciate it if you could provide any insight on the matter.
Many Thanks!
Faiz

**Comment by davek44** [comment]
Hi Faiz, the error seems to indicate that the train/valid/test sequences in sequences.bed request an interval that is outside of the coverage files. Could you double check that all files agree on the genome assembly? You could specifically load in the coverage file and sequences.bed into a genome browser to verify. You could also use pdb to put a breakpoint when that error occurs to identify the precise problematic interval.

**Comment by FaizRizvi** [comment]
Thank you very much for your insight Dr. Kelley. I will try to take a closer look at it using pdb. 

Thank you !
Faiz
