### ISSUE TITLE
 `sad.ipynb` get some abnormal output

### ISSUE THREAD

**Issue by Licko0909** [calico/basenji#35]
`sad.ipynb` get some abnormal output, and no error in front.

This is mine：
![image](https://user-images.githubusercontent.com/27897166/56293118-17c1b600-615b-11e9-9bca-5d877b2d4a28.png)

This is your ipynb file output
![image](https://user-images.githubusercontent.com/27897166/56293216-450e6400-615b-11e9-936e-4c9d7964997c.png)

BTW, I want to ask a question. In 'train_test.ipynb', is my training process normal? The above is my run, the following is the original tutorial run

![image](https://user-images.githubusercontent.com/27897166/56292768-53a84b80-615a-11e9-93fe-49596004d26c.png)

Best wish!

**Comment by Licko0909** [comment]
Hello! This problem is solved after I use the model you provided, but if I use my own trained model, the above mentioned abnormal output will appear.

**Comment by davek44** [comment]
OK, I'm going to close this issue, and we'll work towards a solution to your remaining problems in the next issue that you posted.
