### ISSUE TITLE
Using the model trained by `train_test.ipynb`, there will be problems with subsequent gene expression predictions, how can I solve it?

### ISSUE THREAD

**Issue by Licko0909** [calico/basenji#36]
Dear developer

I don't know if there is a problem with my operation, I hope I can get your help. I am learning to use basenji because I think basenji is very good, thank you very much!

If I use the model trained by `train_test.ipynb` for the subsequent `gene.ipynb`, `sat.ipynb`, an abnormal prediction will occur.

**I took the latest basenji and my environment installation is done according to the tutorial you said.**

The `train.tfr` file output by my `preprocess.ipynb` and my trained model, as long as it is my own training model, no matter how good AUPRC, will get the abnormal output.

Specifically, as I retrain the model, the training process and results are as follows:

![image](https://user-images.githubusercontent.com/27897166/56348585-58700c80-61f9-11e9-9318-f65893dc84c3.png)

![image](https://user-images.githubusercontent.com/27897166/56348536-38d8e400-61f9-11e9-953a-0d424b72999f.png)

![image](https://user-images.githubusercontent.com/27897166/56348614-6f166380-61f9-11e9-8100-337d4b825dac.png)

**I put my trained model into `gene.ipynb` and the result is still an abnormal result.**
![image](https://user-images.githubusercontent.com/27897166/56348747-b69cef80-61f9-11e9-9a1d-d8841016bc04.png)

![image](https://user-images.githubusercontent.com/27897166/56348784-c7e5fc00-61f9-11e9-85b9-7ea770b38708.png)

**This is the result of the model `model_best.tf` I trained, applied to `sad.ipynb`.**
![image](https://user-images.githubusercontent.com/27897166/56348684-90774f80-61f9-11e9-8772-ad9bd1ea26ce.png)

**Later I downloaded and used the model you gave** and put it into `gene.ipynb`. I successfully reproduced the original result in `gene.ipynb`.

![image](https://user-images.githubusercontent.com/27897166/56350935-8b68cf00-61fe-11e9-8e7f-9fbb58ae5bc4.png)

![image](https://user-images.githubusercontent.com/27897166/56350955-96bbfa80-61fe-11e9-8765-848ec889bc60.png)

So this shows that the `train.tfr` that my preprocess.ipynb got is problematic, which caused my training process to be less normal. **Although I can achieve stable convergence in the end, I can get a higher AUPRC in the test phase**, but my initial training process shows that the loss is very low. as follows:

![image](https://user-images.githubusercontent.com/27897166/56348585-58700c80-61f9-11e9-9318-f65893dc84c3.png)

This is also the place I am troubled. When I execute `preprocess.ipynb`, I sometimes can't get the `train.tfr` and `valid.tfr` files. Last time I passed the `chmod 777 *` command, I modified /basen/basenji and The file permissions in /basenji/bin are output to the tfr file.

I don’t know if my environment is wrong or something else.

**Comment by davek44** [comment]
Hi, my hunch is that your TFRecords training files have a problem. I have two scripts that help you study those files:
https://github.com/calico/basenji/blob/master/bin/tfr_qc.py
https://github.com/calico/basenji/blob/master/bin/tfr_hdf5.py

Could you use those to plot the distribution of values for each target in the TF Records? If you're having trouble, you could also send them to me, and I'll take a look.
