### ISSUE TITLE
Some problem about `sat_mut.ipynb`：NameError: name 'bed_file' is not defined

### ISSUE THREAD

**Issue by Licko0909** [calico/basenji#37]
Hello! dear developer, I don't know if there is a problem with my operation, I hope I can get your help. I am learning to use basenji because I think basenji is very good, thank you very much!

The following is to use the 'models/heart/model_best.tf.meta' model file you provided.

- **This is the basenji I pulled on April 5th.**

The first step of `sat_mut` has no errors.
![image](https://user-images.githubusercontent.com/27897166/56350208-d550b580-61fc-11e9-8bbd-7621ecb6b22b.png)

The second step has an error, KeyError: 'index'
![image](https://user-images.githubusercontent.com/27897166/56349825-f5cc4000-61fb-11e9-88a6-3ac1df1ab992.png)

- **This is the basenji I pulled today.**

The first step of `sat_mut` has an error, NameError: name 'bed_file' is not defined, but I obviously have the `data/gata4.bed` file.
![image](https://user-images.githubusercontent.com/27897166/56350306-0df08f00-61fd-11e9-9c2e-6d09fa27c0c2.png)

**Comment by davek44** [comment]
Hi, thanks for pointing these out. The latest version will have both of these problems fixed.
