### ISSUE TITLE
basenji_data sample_pct

### ISSUE THREAD

**Issue by ckergal** [calico/basenji#38]
Hi Dave,

Thank you for providing such a great tool!
In the tutorial [basenji_data](https://github.com/calico/basenji/blob/master/tutorials/preprocess.ipynb), I have a question regarding the `-d` option when it is set  below 1 as in the  tutorial (`-d .1`).
It seems that the subsequent sequences.bed file mixed train/valid/test regions in random orders using `random.sample` function:
`    mseqs = random.sample(mseqs, int(options.sample_pct*len(contigs)))`

Therefore, could this lead to an issue when the TF records are written i.e when the loop goes through each label, it will write the 256 next sequences (`seqs_per_tfr` option) whatever their  labels?

Thank you again for your help on this.

Best regards,

Camille

**Comment by davek44** [comment]
Hi Camille, you're right that code breaks the split. Thanks for catching this. I just pushed a fix.
