### ISSUE TITLE
Meaning of the test data's result from kipoi

### ISSUE THREAD

**Issue by yuetang625-UT** [calico/basenji#48]
hi, I used the kipoi version of basenji and got the results like this. 
![image](https://user-images.githubusercontent.com/54342920/66611637-c97af600-eb84-11e9-8007-a42ab19920c7.png)
I knew the meaning of the preds/m/n, but what did the specific number mean in the pic above? there are lots of data for this small test data, Is it the expression results of each region on a different sample, I need to add them up in order to obtain a final prediction level? or it is just a score? If I want to know the expression level of specific genes, do you have any suggestions for me with basenji?

**Comment by davek44** [comment]
Questions about Kipoi output are best directed to the leaders of that project; I’m not familiar with how they’re using Basenji.

For predictions relative to a gene annotation, see this tutorial https://github.com/calico/basenji/blob/master/tutorials/genes.ipynb

**Comment by yuetang625-UT** [comment]
thanks for your reply. I have tried the GitHub basenji prediction with basenji_sed.py. It successfully gave me the expression results. However, I'm not sure what's the definition of gene expression. I'm curious that in the publication it seems the training results are the 128 bin coverage for different cell types. So how does basenji link the coverage with the expression? Does this method use TSS coverage to predict the expression?  I suppose here the gene expression level is not the FPKM score.

**Comment by davek44** [comment]
Yes, it’s using predicted activity in the 128 bp bin that covers the gene’s TSSs to describe its expression. I have a preprocessing step that takes in a GTF to determine those positions.

**Comment by yuetang625-UT** [comment]
Thank you for the explanation.
