### ISSUE TITLE
basenji_train.py has bugs when running according to your tutorial

### ISSUE THREAD

**Issue by tomcat123a** [calico/basenji#49]
I installed tensorflow-gpu,version 1.4,
and downloaded the data according to your tutorial.
[https://github.com/calico/basenji/blob/master/tutorials/train_test.ipynb](url)
.Then I ran the code at cell 2,
![image](https://user-images.githubusercontent.com/12189033/68326988-8421e980-009a-11ea-88e7-db204210396a.png)

basenji_train.py --augment_rc --ensemble_rc --augment_shifts "1,0,-1" --logdir models/heart --params models/params_small.txt --train_data data/heart_l131k/tfrecords/train*.tfr --test_data data/heart_l131k/tfrecords/valid*.tfr

Then a bug was given as below,"local variable 'metrics_queue' referenced before assignment".
![image](https://user-images.githubusercontent.com/12189033/68326929-60f73a00-009a-11ea-9f98-a2b993176dc7.png)

Could you please help solve the problem?
Thanks a lot.

**Comment by davek44** [comment]
Thanks for the bug report. I just pushed the fix
