### ISSUE TITLE
GC bias correction

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [calico/basenji#50]
In the paper you mention how GC% bias correction was performed:

> We normalized for GC% bias using a procedure that incorporates several established ideas, aiming to model the trend across the GC% spectrum without precluding a GC% enrichment for active regions( Benjamini and Speed 2012; Teng and Irizarry 2016). We assigned each position an estimated relevant GC% value using a Gaussian filter (to assign greater weight to nearby nucleotides more likely to have been part of a fragment relevant to that genomic position). Then we fit a third-degree polynomial regression to the log2coverage estimates. Finally, we reconfigured the coverage estimates to highlight the residual coverage unexplained by the GC% model. The parameters of the bias models exhibit a wide range, both within and across assays, suggesting the absence of a common sequencing bias. A Python script implementing these procedures to transform a BAM file of alignments to a BigWig file of inferred coverage values is available in the Basenji tool suite.

I couldn't locate the script you are talking about, where is it? :smile:

**Comment by Maarten-vd-Sande** [comment]
My bad, I found it
https://github.com/calico/basenji/blob/master/bin/bam_cov.py

**Comment by Maarten-vd-Sande** [comment]
Where is this sentence going?
https://github.com/calico/basenji/blob/d0b345561029dd749e068775984bfd7bd7211421/bin/bam_cov.py#L54-L56

**Comment by davek44** [comment]
Can't remember! It's very possible that I never actually chose a recommended approach.

**Comment by Maarten-vd-Sande** [comment]
Ok too bad, thanks for the reply!
