### ISSUE TITLE
`crop_bp` argument in `basenji_data_read.py`

### ISSUE THREAD

**Issue by ch6845** [calico/basenji#55]
I am following tutorials in [`tutorials/preprocess.ipynb`](https://github.com/calico/basenji/blob/fd1e1d5c07b3268f2f9bffe9b48929ead7aa9831/tutorials/preprocess.ipynb) to reproduce the data used in the publication step-by-step.

However, I got an error message executing the command
`!basenji_data.py -d .1 -g data/unmap_macro.bed -l 131072 --local -o data/heart_l131k -p 8 -t .1 -v .1 -w 128 data/hg19.ml.fa data/heart_wigs.txt`

It was because `basenji_data.py` forces to set --crop parameter larger than 0.
In line 69 of `basenji_data_read.py`, ` assert(options.crop_bp > 0)`

Could you help with it?

Additionally, I have another trivial question. The command has an argument -d with 0.1. Does it mean that output is subsample of data used in the publication?

Sincerely Yours

**Comment by davek44** [comment]
Thanks for finding that. I just pushed a fix.

Yes, the tutorial dataset is much smaller than those studied in the manuscript. It's just there to show you how to run the programs.
