### ISSUE TITLE
Use of slurm code

### ISSUE THREAD

**Issue by ckergal** [calico/basenji#62]
Hello David,

I'd like to launch basenji_train.py on a cluster with slurm, but I'm not sure about how to deal with it. Please, do you have a kind of example like your tutorials to help ?
Thank you !

**Comment by davek44** [comment]
You may have noticed slurm code sprinkled around the repo. I primarily use it for launching parallel GPU jobs, such as scoring a large set of SNPs by breaking up the set to be handled by separate jobs. I don't use anything fancy to train models. You should be able to stick the commands from the training tutorial notebook into a script and launch if with sbatch. For details about how to configure to use GPUs on your particular cluster, I'd reach out to your cluster IT folks.

**Comment by ckergal** [comment]
Sorry, I have not seen the latest updates. Thank you so much !
