### ISSUE TITLE
akita_data.py using a lot of RAM

### ISSUE THREAD

**Issue by papelypluma** [calico/basenji#71]
Hi basenji/akita developers, I'd just like to ask if it's normal that akita_data.py is using a lot of RAM (while only using 1 process, although -p was set to 8). I've been running it for quite some time (~9H), but no output files other than the options.json can be seen. RAM utilization just keeps rising. I'm not sure if I'm doing it right. I'm following https://github.com/calico/basenji/blob/master/manuscripts/akita/tutorial.ipynb

Thanks for any help on this.

**Comment by gfudenberg** [comment]
Hi, that's surprising! I'm seeing closer to 1Gb usage for 8 processes when running that step in the tutorial notebook and the output should direct to ./data/1m/. Is there any printed output or error messages you are seeing?

**Comment by papelypluma** [comment]
Hi @gfudenberg. Thanks for the reply. No, there wasn't any printed output nor error messages when I first tried it. I tried it again the other day by specifying a --break value besides 0, and it's currently running at constant RAM utilization. For my first attempt, I initially set --break to zero. I'm wondering if there's a rough guide on how --break -l --stride_train and --stride_test should be set with respect to each other. Thank you!

**Comment by gfudenberg** [comment]
The parameters in the notebook should be good defaults for human/mouse,
apart from --sample 0.05, which just downsamples the number of segments
used to make the example run more quickly and should be removed for serious
model training. Other organisms with very different genome sizes or feature
sizes might need very different settings.

--break should get a default value of ~8Mb (
https://github.com/calico/basenji/blob/10fea4c2045ccf422b18e94933e62c358da4f555/bin/akita_data.py#L53).
I can see how a value of zero for --break would lead to issues. We can
update the code to raise an error if --break < window size.

**Comment by davek44** [comment]
--break breaks the chromosomes into smaller contigs when they are larger than the specified size. Setting it to zero might have isolated every nucleotide as its own contig, which would explain the memory blowup. Definitely safer to stick with the notebook or default values there. I'll add some checks into the script to catch bad values.

**Comment by papelypluma** [comment]
@gfudenberg and @davek44, thanks for the explanations!
