### ISSUE TITLE
New stable release?

### ISSUE THREAD

**Issue by abretaud** [calico/basenji#74]
Hi!
I'm working on a conda package for basenji in https://github.com/bioconda/bioconda-recipes/pull/26534
As available releases of basenji seem to be old compared to latest developments in the master branch, I've written the recipe to use a recent commit from master. Do you think it's ok? Or should I stick to the released 0.4? Or do you plan to make a new release any time soon?

Second question: [envrionnment.yml](https://github.com/calico/basenji/blob/master/environment.yml#L9) refers to cudnn and cudatoolkit. Are they only needed when using tensorflow-gpu, or is it always required by basenji?

**Comment by davek44** [comment]
Thanks! The master branch is much better than the previously released versions right now. Would it be helpful if I did a 0.5 release?

cudnn and cudatoolkit are only required for GPU usage. It's probably best to leave them out and let the user figure it out or let the anaconda tensorflow dependencies sort it out.

**Comment by abretaud** [comment]
Ok thanks for the quick answer!
Yes, a 0.5 release would be great if possible :)
:+1: for the gpu dependencies, I'll just leave them out

**Comment by davek44** [comment]
I just made a few updates and released 0.5

**Comment by abretaud** [comment]
Cool, many thanks!

**Comment by abretaud** [comment]
Hi! seems like I encountered the bug fixed in https://github.com/calico/basenji/commit/525a9ab12e0c560a844eca72c71687f5a3e0e3d6, any chance to get a new release?

**Comment by davek44** [comment]
Ah, my mistake. I did a new release https://github.com/calico/basenji/releases/tag/0.5.1

**Comment by abretaud** [comment]
Wonderful, thanks a lot!
