### ISSUE TITLE
input.shape[1] in layers.py from tf2_hic branch is an int, so has no value attribute

### ISSUE THREAD

**Issue by abureau** [calico/basenji#78]
From the explore_model.ipynb notebook. The notebook uses TensorFlow 1.15, I have TensorFlow 2.4.

I ran:

model_dir = './'
params_file = model_dir+'params.json'
model_file  = model_dir+'model_best.h5'
with open(params_file) as params_open:
    params = json.load(params_open)
    params_model = params['model']
    params_train = params['train']

seqnn_model = seqnn.SeqNN(params_model)

AttributeError: in user code:

    /lustre03/project/6000443/basenji/basenji/layers.py:496 call  *
        seq_len = inputs.shape[1].value

    AttributeError: 'int' object has no attribute 'value'

When I debug with pdb, I get 

(Pdb) inputs.shape
TensorShape([None, 448, 448, 48])
(Pdb) inputs.shape[1]
448
(Pdb) inputs.shape[1].value
*** AttributeError: 'int' object has no attribute 'value'

This happens also when I run akita_train.py.

I noticed this has been rewritten in layers.py from the master branch. Is merging the branches the solution?

**Comment by davek44** [comment]
Are you on a branch other than master? The master branch should be good for using Akita

**Comment by abureau** [comment]
I was using the tf2_hic, relying on the preprint at https://www.biorxiv.org/content/10.1101/800060v1 which indicates: "All code used for training Akita available at: https://github.com/calico/basenji/tree/tf2_hic/". I had not noticed tf2_hic had been merged into the master branch. The Nature Methods paper does point to the master branch. Switching to the master branch has solved this issue.
