### ISSUE TITLE
Cross-species models?

### ISSUE THREAD

**Issue by richardshuai** [calico/basenji#82]
Are the model_human.h5 and model_mouse.h5 models obtained from  https://github.com/calico/basenji/blob/master/manuscripts/cross2020/get_models.sh trained on human only and mouse only data respectively? Or is each model jointly trained on human and mouse and then finetuned on human only or mouse only?

I am planning on replacing the last layer of model_human.h5 to predict ATAC-seq profiles but wanted to first know which models from the paper I'm working with. Thanks!

**Comment by davek44** [comment]
Those models were jointly trained on both species and then fine-tuned on the respective species.
