### ISSUE TITLE
Errors importing module when running tutorial script

### ISSUE THREAD

**Issue by ziyuanzhao2000** [calico/basenji#85]
Hi David,

Thanks for developing this very useful tool. I'm currently trying to follow the tutorial to understand the workflow. However, after I trained the model and tried to follow the tutorial on testing gene expression predictions, I get error from running the py script basenji_test_genes.py. It says that 

```
Traceback (most recent call last):
  File "bin/basenji_test_genes.py", line 42, in <module>
    from basenji import batcher
ImportError: cannot import name 'batcher'
```

Indeed, I can't find the module 'batcher' from the repo I pulled recently. Your help is appreciated as to how to fix this issue. Thanks!

**Comment by davek44** [comment]
Hi, sorry about that. The test genes script is deprecated. I never found gene specific prediction to be terribly useful. We’ll probably revisit this with the new Enformer model at some point.

**Comment by davek44** [comment]
My latest commit properly deprecates this old code.
