### ISSUE TITLE
SAD scores Questions

### ISSUE THREAD

**Issue by meeramehta** [calico/basenji#86]
I noticed I can still get SAD scores for my SNPs without using any target labels (i.e no -t option/argument). How do I interpret these scores?
The SAD score is defined as "the predicted change in aligned fragments to the region", which region is this referring to?
Also, is there a scale/unit/range for the SAD scores?

**Comment by davek44** [comment]
Hi, the -t option is used to filter the targets to a subset. What the targets represent depends on which model you’re using. The SAD scores compute the difference between alleles for the sums across the sequence length, so the “region” refers to the sequence length. The scale of the predictions is determined by the number of predicted aligned reads in that region, so it depends on the dataset sequencing depth and activity in the region.

**Comment by meeramehta** [comment]
Thank you!
