### ISSUE TITLE
Sequence positions for test sequences

### ISSUE THREAD

**Issue by pkathail** [calico/basenji#87]
Hi,

First of all, thanks for developing and maintaining this repo!

I'm using Basenji and have a set of test predictions, which I want to map back to the chromosome/start/stop positions of the sequences. I was doing this semi-manually by referring back to the `sequences.bed` file, but noticed that the order of test sequences in `sequences.bed` seemed to differ from `targets.h5` in the test output (I checked this by comparing the rows in the `seqs_cov/` h5s corresponding to the test set to `targets.h5`).

I noticed you recently introduced an option in `basenji_test.py` to write out bedgraph files with position information, but it seems like it's doing this same mapping with `sequences.bed`. Have you also encountered this re-ordering of the test sequences? If so, do you have suggestions to prevent or work around it?

Thanks!
Pooja

**Comment by davek44** [comment]
Hi Pooja, I think that the sequence order is maintained. There are some additional modifications to the values that occur in basenji_data_write.py which loads the seqs_cov h5 files and writes the final train/test TFRecords. Could that be explaining the differences that you see? If not, could you pass along some more details that might help me track down the issue?

**Comment by pkathail** [comment]
Hi David -- yes, you're right. When I compare the test TFrecords to `targets.h5` the order is exactly the same. I'll take a closer look at basenji_data_write to understand the processing being done there. Thanks for your help!

**Comment by pkathail** [comment]
Following up on this --

I confirmed that the sequence order in my test TFrecords and `targets.h5` is in fact the same. However, I took a closer look at basenji_data_write.py and I'm not passing in any of the flags that would do additional modifications, but the values in my seqs_cov files and TFrecords are different. Although the unsorted values are different, if you sort the values for a single target, the sorted seqs_cov and TFrecords values are the same, which makes me think it is a re-ordering problem. But I've looked through your code in basenji_data.py and basenji_data_write.py and don't see an obvious place where any reordering might be happening. 

Please let me know if you see this issue as well, or if I'm missing something obvious! The reason I ask about this is that I'm trying to map predicted values back to their sequence positions -- if you have other suggestions for how to do that, please let me know as well. 

Thanks for your help!

For reference, here's how I did the comparison:
```
import numpy as np
import pandas as pd
import h5py
from basenji import dataset

# load data, we'll just check this for the 9th target for now
ti = 9
mseqs = pd.read_csv(f"{data_dir}/sequences.bed", sep="\t", names=["chr", "start", "end", "fold"])
seqs_cov = h5py.File(f"{data_dir}/seqs_cov/{ti}.h5", "r")["targets"][:,:]
targets = h5py.File(f"{test_dir}/targets.h5", "r")["targets"][:,:,:]
eval_data = dataset.SeqDataset(data_dir, split_label="test", batch_size=64, mode='eval')
tf_seqs, tf_targets = eval_data.numpy() 

# split the seqs_cov file into just the test set indices
test_set_indexes = mseqs[mseqs["fold"] == "test"].index.values
test_seqs_cov = seqs_cov[test_set_indexes, :]

# flatten all arrays for easy comparison
test_seqs_cov_ti = test_seqs_cov.flatten()
test_targets_ti = targets[:,:,ti].flatten()   # data only has one bin, so we can ignore the 1st axis
tf_targets_ti = tf_targets[:,:,ti].flatten()   # data only has one bin, so we can ignore the 1st axis

print("Total # of test sequences: ", test_seqs_cov_ti.shape[0])
# confirm TFrecords and targets.h5 are in same order
print("# of non-matching positions (TFrecords vs targets.h5): ", len(np.where(tf_targets_ti != test_target_ti)[0]))
# compare seqs_cov and TFrecords
print("# of non-matching positions (seqs_cov vs TFrecords): ", len(np.where(test_seqs_cov_ti != tf_targets_ti)[0]))
print("# of non-matching positions (sorted): ", len(np.where(np.sort(test_seqs_cov_ti) != np.sort(tf_targets_ti))[0]))
```

Output:
```
Total # of test sequences:  1200292
# of non-matching positions (TFrecords vs targets.h5):  0
# of non-matching positions (seqs_cov vs TFrecords):  1187807
# of non-matching positions (sorted, seqs_cov vs TFrecords):  0
```

**Comment by davek44** [comment]
That's odd. Are you sure the unmappable region code isn't modifying the targets?

My preferred approach for visualizing targets and predictions on the genome right now is currently to use basenji_test.py with the --save --bi 1,2,3 options to write bedgraph files that can be loaded into genome browsers.

**Comment by pkathail** [comment]
I'm pretty sure the unmappable region code isn't modifying my targets. I'm not passing in an unmappable array and `umap_clip` is set to 1. And it's pretty unlikely that the sorted seqs_cov and TFrecords would match if the targets had been modified.

It looks like the `write_bedgraph()` function uses the `sequences.bed`, so it relies on the same assumption that the row ordering is the same?

**Comment by davek44** [comment]
Maybe the best way to proceed would be for you to pass along a minimal example to produce the error, so I can take a closer look.

**Comment by pkathail** [comment]
My colleague figured out that it seems to be the use of `tf.data.Dataset.list_files()` in SeqDataset that causes a reordering. Changing this line
```
dataset = tf.data.Dataset.list_files(tf.constant(tfr_files), shuffle=False)
```
to
```
dataset = tf.data.Dataset.from_tensor_slices(tfr_files)
```
seems to do the trick.

[Here](https://drive.google.com/file/d/1qNtCF7Flz07JVUHflkRwFxOe03a5xqy8/view?usp=sharing) is a small set of example files if you'd like to reproduce my steps below:
```
import pickle
from basenji import dataset 
from basenji import dataset_2 # a copy of dataset.py where I made the change mentioned above

with open("seqs_cov_subset.p", "rb") as f:
    seqs_cov = pickle.load(f)

eval_data_1 = dataset.SeqDataset(data_dir, split_label="test", batch_size=64, mode='eval', tfr_pattern=None)
seqs_1, targets_1 = eval_data_1.numpy()  
np.where(seqs_cov != targets_1)  

eval_data_2 = dataset_2.SeqDataset2(data_dir, split_label="test", batch_size=64, mode='eval', tfr_pattern=None)
seqs_2, targets_2 = eval_data_2.numpy()  
np.where(seqs_cov != targets_2)   
```

**Comment by pkathail** [comment]
Thank you!

**Comment by davek44** [comment]
Yup, thanks for catching that. I pushed that fix, too, now.

**Comment by pkathail** [comment]
thanks!
