### ISSUE TITLE
Requesting for the Tutorial to test gene expression predictions.

### ISSUE THREAD

**Issue by Gunjan-Dixit** [calico/basenji#89]
Hello Basenji developers,

Thank you for providing the tutorials and code for easy implementation. I am a newbie in the deep learning field and I am trying to predict gene expression from the sequence. It would be really helpful if you could share the tutorial to predict gene expression.  

Thank you.

Regards,
Gunjan

**Comment by davek44** [comment]
Hi Gunjan, the original code to aggregate predictions at the gene level has been deprecated for the time being. Your best bet for the moment is to use basenji_predict_bed.py for a BED file centered at the gene TSS of interest to you. You can use the -l option to specify how wide of a region you'd like to consider. I'll recommend 256 bp.

**Comment by Gunjan-Dixit** [comment]
Thank you so much.
