### ISSUE TITLE
basenji_sad_viz.ipynb data

### ISSUE THREAD

**Issue by meeramehta** [calico/basenji#90]
Hi, How can we create the coverage.w5 files for the targets used in basenji_sad_viz.ipynb?
I can't seem to find the ones used in the example. Have these been released somewhere?
Thank you, Meera

**Comment by davek44** [comment]
Hi, those files are my bespoke storage format for the processed training datasets that I have stored on our Calico servers. That notebook wasn't really written with the public in mind; sorry about that. If there are particular tracks that you're interested in, I can share them.

**Comment by meeramehta** [comment]
Thank you for the quick response. Yes, could you share the tracks for these identifiers: CNhs12531, CNhs12179, CNhs12354, CNhs11957,  CNhs12003, CNhs11958, CNhs12333, CNhs13437.

**Comment by davek44** [comment]
Hi, you can download those files from the google cloud bucket here: gs://seqnn-share/meeramehta/

**Comment by meeramehta** [comment]
For the SAD prediction, what is the start and endpoint of the sequence length that it is making a prediction for?

**Comment by davek44** [comment]
The script will use whatever you specify in your parameters file, which happens right here: https://github.com/calico/basenji/blob/master/bin/basenji_sad.py#L205

If I trained with 131k sequences, I generally half it to 65k sequences for SNP prediction because the dilated convolutions can't see beyond that so you save computation.

**Comment by meeramehta** [comment]
Have the dimensions/keys of the sad.h5 file changed since this notebook was written? The sad.h5 I got from running basenji_sad.py on my vcf file with 197 SNPs didn't give me the same keys as the 'ponies_sad/sad.h5' that is used in the notebook. Just trying to find out how to use visualize the SAD scores

**Comment by davek44** [comment]
Yes, that's quite possible that the keys have changed. REF and ALT store the predictions across the length of the sequence. That can be a lot of data, so you have to tell the script to save them by specifying --stats "SAD,REF,ALT".

**Comment by meeramehta** [comment]
Thanks!
