### ISSUE TITLE
can't run get_data.sh 

### ISSUE THREAD

**Issue by bo-wang-up** [calico/basenji#93]
When I run the code "bash get_data.sh", the fault "syntax error near unexpected token `newline'" is displayed. I searched for solutions, and I was advised to remove the '<' and '>'. But there are so many '<' and '>' in the .sh file. How can I handle the problem.

**Comment by davek44** [comment]
Could you be more specific about which file you're talking about? I don't see any "<" or ">" in manuscripts/genome_research2018/get_data.sh or manuscripts/akita/get_data.sh.

**Comment by bo-wang-up** [comment]
Sorry. It is manuscripts/akita/get_data.sh. When I run the file, the fault " syntax error near unexpected token `newline' " is displayed. I open it with pycharm, and one line in it is `<link rel="dns-prefetch" href="https://github.githubassets.com">`

**Comment by bo-wang-up** [comment]
Sorry. It is manuscripts/akita/get_data.sh. When I run the file, the fault " syntax error near unexpected token newline' " is displayed. I open it with pycharm, and one line in it,  `<link rel="dns-prefetch" href="https://github.githubassets.com">`

**Comment by davek44** [comment]
I'm not sure what's going on there. The script here: https://github.com/calico/basenji/blob/master/manuscripts/akita/get_data.sh is working fine for me, and I don't see any of the text that is giving you problems. Maybe reinitialize the repo with a fresh clone.

**Comment by bo-wang-up** [comment]
OK. I just download this ''get_data.sh'' file. Now the problem has been solved. Thanks!
